categories: []
description: Minfi Bioconductor package
homepage_url: http://bioconductor.org/packages/release/bioc/html/minfi.html
long_description: Minfi package version 1.16.0, Analyze illumina human methyaltion 450K arrays
name: minfi
owner: nturaga
