config_version: 0.3
genome_folder: /Users/nagampv/Desktop/nagampv_projects/refgenie/genome_folder
genome_servers: ['http://refgenomes.databio.org']
genomes:
  hg38_chr22:
    assets:
      fasta:
        tags:
          default:
            asset_digest: 8363ebef6fda649746c93e832b4fc940
            asset_children: ['hg38_chr22/bwa_index:default', 'hg38_chr22/star_index:default']
            seek_keys:
              fasta: hg38_chr22.fa
              fai: hg38_chr22.fa.fai
              chrom_sizes: hg38_chr22.chrom.sizes
            asset_parents: []
            asset_path: fasta
        default_tag: default
      bwa_index:
        tags:
          default:
            seek_keys:
              bwa_index: hg38_chr22.fa
            asset_parents: ['hg38_chr22/fasta:default']
            asset_path: bwa_index
            asset_digest: 3b0cd42e50841941f4e20b1bffe19f0f
        default_tag: default
      star_index:
        tags:
          default:
            seek_keys:
              star_index: .
            asset_parents: ['hg38_chr22/fasta:default']
            asset_path: star_index
            asset_digest: 3d40fdd667ffc7c2c18fee80173e4e68
        default_tag: default
  human_rDNA:
    assets:
      fasta:
        tags:
          default:
            asset_digest: e18c0446f55f2584bf58f04076400ce6
            asset_children: ['human_rDNA/bowtie2_index:default', 'human_rDNA/bwa_index:default']
            seek_keys:
              fasta: human_rDNA.fa
              fai: human_rDNA.fa.fai
              chrom_sizes: human_rDNA.chrom.sizes
            asset_parents: []
            asset_path: fasta
        default_tag: default
      bowtie2_index:
        tags:
          default:
            seek_keys:
              bowtie2_index: human_rDNA
            asset_parents: ['human_rDNA/fasta:default']
            asset_path: bowtie2_index
            asset_digest: a794ca7b0183e614855533d5407cf199
        default_tag: default
      bwa_index:
        tags:
          default:
            seek_keys:
              bwa_index: human_rDNA.fa
            asset_parents: ['human_rDNA/fasta:default']
            asset_path: bwa_index
            asset_digest: aa0e2c0cfa502a5041e140e1e11c4259
        default_tag: default
  rCRSd:
    assets:
      fasta:
        tags:
          default:
            asset_digest: 4eb430296bc02ed7e4006624f1d5ac53
            asset_children: ['rCRSd/bwa_index:default']
      bwa_index:
        tags:
          default:
            seek_keys:
              bwa_index: rCRSd.fa
            asset_parents: ['rCRSd/fasta:default']
            asset_path: bwa_index
            asset_digest: de383551ccf544bd9bbee7d4c529f39b
        default_tag: default
  human_alu:
    assets:
      fasta:
        tags:
          default:
            asset_digest: 9e8fa06e6125f89be4fb974879cb91a6
            asset_children: ['human_alu/bwa_index:default']
      bwa_index:
        tags:
          default:
            seek_keys:
              bwa_index: human_alu.fa
            asset_parents: ['human_alu/fasta:default']
            asset_path: bwa_index
            asset_digest: 569e7f34dc5fa323c8aca50f1b278004
        default_tag: default
