categories:
- Metagenomics
description: Convert Kraken output to BIOM.
long_description: |
  Convert kraken's tabular output to BIOM format, using genbank taxonomy to interpret
  numeric IDs. Allows clustering by taxonomic rank.
name: kraken_to_biom
owner: iuc
homepage_url: https://github.com/galaxyproject/tools-iuc/blob/master/tools/kraken/kraken_to_biom/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/blob/master/tools/kraken/kraken_to_biom/
type: unrestricted